# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Product.create([
  { :name => "Gameboy", :description => "Handheld gaming device", :price => "50.00", :haveit => false, :created_at => "2013-08-12 20:06:32", :updated_at => "2013-08-12 22:57:18" },
  { :name => "Backpack", :description => "Broken, but still works.", :price => "12.00", :haveit => true, :created_at => "2013-08-12 20:23:49", :updated_at => "2013-08-12 23:02:04" },
  { :name => "Water Bottle", :description => "Brand new!", :price => "3", :haveit => false, :created_at => "2013-08-12 20:30:15", :updated_at => "2013-08-12 23:02:33" },
  { :name => "Stuff", :description => "There are things there.", :price => "19", :haveit => true, :created_at => "2013-08-12 21:39:37", :updated_at => "2013-08-12 23:03:01" },
  { :name => "Pencil", :description => "Something very expensive", :price => "1000.99", :haveit => false, :created_at => "2013-08-12 21:53:28", :updated_at => "2013-08-12 23:03:38" }
], :without_protection => true )


